#!/bin/bash

#this script quarries a mysql database for user rss feeds
#1st argument: Database name
#2nd argument: mysql user name
#3rd argument: mysql user password
#4th argument: table name
#5th arguement: id (in table)
#The feed urls are then piped into the rssParser


echo "select feed1, feed2, feed3, feed4, feed5 from $4 where id = \"$5\";" | mysql -u $2 -p$3 $1 | \
tail -n 1 | sed 's_ _\\&_g' | tr '\t' ' ' | xargs ./rssParse
