#!/bin/bash

#this script pulls headlines from ESPN.com
#appends the headline's URL followed by the headline
#onto the file ESPNHeadlines
#This file is capped at 100 lines

java URLConnectionReader http://espn.go.com | sed ':begin;$!N;s/\n/~~~~~/;tbegin' | \
sed 's_</script><!-- begin InContent ad -->_\n&_g' | egrep -v '^</script><!-- begin InContent ad -->' | \
sed 's_~~~~~_\n_g' | grep '^<li><a href="http://' | \
sed 's_</a>_\n&_g' | grep '^<li><a href="http://' | \
sed 's_>_&\n_g' | sed 's_href="\(.*\)"_\n\1_g' | \
sed 's_"_\n"_g' | egrep -v '"|"' | \
egrep -v '^<li>$|^<a $' >> ESPNHeadlines
cat ESPNHeadlines | tail -100 > temp.tmp
mv temp.tmp ESPNHeadlines
