#!/bin/bash
#This script takes headline files as arguments
#it goes through each and contructs an html file and outputs to stdout
#This script takes one argument-the name of the html file the output wil become,
#  this is necessary for the auto-refresh feature


  echo \<HTML\>
  echo \<HEAD\>
  echo \<link href=\"headline.css\"\ rel=\"stylesheet\"\ type=\"text/css\"\ media=\"screen\"/\>
  echo \<meta\ http-equiv=\"refresh\"\ content=\"300\"\;URL=\"$1\"\>
  echo \</HEAD\>
  echo \<BODY bgColor=Black\>
  echo \<ul\ id=\"main\"\>

  #Here begins headline file manipulation
  sed 's_^http://.*_~&\n&_g' | sed 's_^~http://.*_<div style=\"float: right; margin-left: 10px;\">\n <a name=\"fb\_share\" type=\"button\_count\" share\_url=\"&\" href=\"http://www.facebook.com/sharer.php\">Share</a></div>\n<div></div>\n_g' | \
  sed 's_~http://_http://_g' | \
  sed 's_^http://_<li class=\"mainbar-element\"><a href=\"&_g' | sed 's_<a href.*_&\"_g' | sed 's_<a href.*_&>_g' | \
  tr -d '\n' | sed 's_<_\n&_g' | sed 's_<a href.*_&</a></li>_g'
  echo "<script src=\"http://static.ak.fbcdn.net/connect.php/js/FB.Share\" type=\"text/javascript\"></script>"

  printf "%b\n"
  echo \</ul\>
  echo \</BODY\>
  echo \</HTML\>


