#!/bin/bash

for var in "$@"
do
  java URLConnectionReader $var | \
  sed 's_img_\n&_g' | grep "^img" | \
  sed 's_src[\s]*=[\s]*"_\n&_g' | \
  grep "^src" | \
  sed 's_src[\s]*=[\s]*"[\s]*__g' | \
  sed 's_\s_\n~_g' | \
  grep "^http" | \
  sed 's_"_\n"_g' | \
  grep "^http" | \
  egrep "jpg$|jpeg$|png$|bmp$" | \
  wget -i - -P ./images -A jpg,jpeg,png,bmp -q -nc

done
